### ISSUE TITLE
Compiling with non-ARC makes a big issue

### ISSUE THREAD

**Issue by sidan5** [mutualmobile/MMWormhole#12]
Actually I spent lots of time missing this super simple issue out. Please add to the .m file this lines below the imports:

    #if !__has_feature(objc_arc)
    #error This class requires automatic reference counting
    #endif

**Comment by ConfusedVorlon** [comment]
I'll send a pull request for this one too; It bit me for a while.

**Comment by cnstoll** [comment]
Merged it. Thanks!
