### ISSUE TITLE
Request - please add OSX support to the podspec

### ISSUE THREAD

**Issue by ConfusedVorlon** [mutualmobile/MMWormhole#14]
I'm using it, and it works well! It would be nice to be able to add it through cocoapods.
Thank you.

**Comment by cnstoll** [comment]
Good call. I agree that would be useful. Do you happen to have time to submit a PR for this? If so, that would definitely help. Thanks!

**Comment by ConfusedVorlon** [comment]
done.

**Comment by cnstoll** [comment]
Merged. Thanks!

**Comment by ConfusedVorlon** [comment]
Minor point - but you missed adding OSX in the first sentence of the readme.
