### ISSUE TITLE
Method "listenForMessageWithIdentifier" didn't work if I launch watch app from glance

### ISSUE THREAD

**Issue by yenchenlin1994** [mutualmobile/MMWormhole#16]
#### Here is an simple example project:

<https://github.com/yenchenlin1994/WormholeBugExample>

(You have to change App groups to your own groups)

This app simply use a NSTimer to update counter label on Phone interface,
and then use MMWormhole try to sync value of the label on Watch interface.

It works totally fine when I choose schema **WormholeBugExample WatchKit App**
to run, and then manually open the phone app on iOS simulator.

However, things changed if I change schema to **Glance - WormholeBugExample WatchKit App** and then do the same process as above.

After I tap on Glance to launch my watch app, the label on watch's interface didn't correctly sync with label on phone interface.

In fact, it sometimes stop listening for the message at the beginning or when counter counts to particular value (ex: When it counts to 8).

How can I fix it?

**Comment by cnstoll** [comment]
You should move everything in awakeWithContext into willActivate. That'll help make sure the wormhole is active. It's also the best way to ensure that UI updates only happen when the interface controller is active. It's also a good idea to stop listening and/or nil out the wormhole in the didDeactivate method of the interface controller.

**Comment by yenchenlin1994** [comment]
I've tried your solution,
but problems I met remain the same.

**Comment by davidbarker** [comment]
I seem to be having similar issues when activating my WatchKit app from the glance. The WatchKit app works perfectly when I run it directly from Xcode, but if I run the glance scheme and then tap on it to open the WatchKit app, my callbacks don't run.

**Comment by mikeswanson** [comment]
This has been discussed in the Apple Forums, and based on a response from an Apple employee, it's possible that it's only a simulator bug: https://devforums.apple.com/message/1111028

**Comment by cnstoll** [comment]
Yeah. My understanding is that it's an unfortunate (and fairly annoying until we have hardware) simulator bug.
