### ISSUE TITLE
Use of NSNotificationCenter seems redundant

### ISSUE THREAD

**Issue by jpmhouston** [mutualmobile/MMWormhole#18]
I can spot no benefit to having the CFNotificationCenter callback post a NSNotificationCenter notification. It should be able to just call didReceiveMessageNotification directly, no?

**Comment by cnstoll** [comment]
For whatever reason, listening for and posting the notification seems to be more reliable when I've tested it. I'm not sure why.

There's a slight side benefit to testing by having it in there. Darwin notifications don't seem to be delivered to the sender, so you can test some of MMWormhole's functionality by simulating a message with the NSNotificationCenter. See the Example project's tests for an example.
