### ISSUE TITLE
Pod install does not allow watch files to import MMWormhole class files

### ISSUE THREAD

**Issue by kevinnguy** [mutualmobile/MMWormhole#21]
Hey guys, did a pod install of MMWormhole and I wasn't able to import the class files to my watch extension files. Am I missing something?

**Comment by cnstoll** [comment]
You have to specifically create an extension target in your pod file that references MMWormhole to get it to work. I believe they have some examples of how to do it.

**Comment by pzearfoss** [comment]
For example:
```
platform :ios, '7.0'
xcodeproj 'CB30'

pod 'AFNetworking', '2.5.1'
...
pod 'MMWormhole', '~> 1.1.1'

target 'CB30Tests' do
	pod 'Kiwi', '2.3.1'
end

target 'CB30 WatchKit Extension', :exclusive => true do
	...
	pod 'MMWormhole', '~> 1.1.1'
end
```

**Comment by kevinnguy** [comment]
Thanks for the responses @cnstoll  @pzearfoss :smile:

**Comment by cnstoll** [comment]
++Pat
