### ISSUE TITLE
Swift

### ISSUE THREAD

**Issue by djones** [mutualmobile/MMWormhole#22]
Any plans to write this in Swift? This is the only dependency I have that requires I create a bridging header in my project to get Objective-C support.

**Comment by zweckApp** [comment]
+1 for this request. Just using MMWormhole with an prototype app inside of a Swift custom framework in an Swift app with Swift extensions. Would be nice to use it natively. Any change to make it a framework too?

**Comment by pzearfoss** [comment]
I'd be against this.  The great thing about wormhole is its simplicity.  It probably wouldn't be difficult to reimplement in Swift, but that seems like it should be its own project.

**Comment by cnstoll** [comment]
Hi Dave,

Unfortunately I don't have any plans to write this in Swift. One of the great things about Swift is Apple's support for it in primarily Objective-C based projects. I realize that using a bridging header is a bit of a pain, and can be unfortunate for some all-swift projects. But at this point, I feel like there are more all-Objective-C projects than all-Swift ones, so at least for now I intend to keep MMWormhole as an Objective-C library. Fortunately, this doesn't prevent it from being used in Swift projects!

I would love for libraries like this to be more natively accessible in Swift, but I don't really see a good way to do that without completely forking it into it's own standalone library. At that point you lose the ability to have improvements and fixes apply to both.

Happy to hear additional thoughts here, but right now I don't really see a good way to do this.

Thanks,

- Conrad

**Comment by djones** [comment]
Thanks @cnstoll 

These are very good points. Agreed it would make sense to be a different project.

**Comment by etiennea** [comment]
Would it be possible to explain somewhere how to create that bridging header? I can't seem to get it right I must be missing a step.
