### ISSUE TITLE
listenForMessageWithIdentifier always returns 'nil' in callback messageObject

### ISSUE THREAD

**Issue by NitWitStudios** [mutualmobile/MMWormhole#25]
Trying to use this to communicate from phone to watchKit app and having trouble receiving the messageObject in 'listenForMessageWithIdentifier' callback.
The listener gets fired (confirmed with breakpoints) but the 'messageObject' is always nil.

Phone Code:

    self.wormhole = MMWormhole(applicationGroupIdentifier: "my.group.identifier", optionalDirectory: "wormholeDirectory")
    self.wormhole?.passMessageObject(["sayHello": true], identifier: "wormholeMessageIdentifier")

WatchKit Extension Code:

    self.wormhole = MMWormhole(applicationGroupIdentifier: "my.group.identifier", optionalDirectory: "wormholeDirectory")
    self.wormhole?.listenForMessageWithIdentifier("wormholeMessageIdentifier", listener: { (messageObject) -> Void in
            if let object = messageObject as? [String: AnyObject]
            {
                if object["sayHello"] as Bool
                {
                    ...code...
                }
            }
        })

**Comment by RomainBoulay** [comment]
I do have the same issue here `messageObject` is always `nil`.

**Comment by RomainBoulay** [comment]
I solved my issue, there was a mistake with the entitlements for the app group...

**Comment by NitWitStudios** [comment]
@RomainBoulay  What was the mistake? I have checked all my app group settings and all seems good (as far as I can tell).
I can build and run the app and extension on Simulator as well as run the main app (not the extension) on my iPhone 6.
Am I missing something??

Developer Portal - Both App Certificates (App + Extension) have App Groups enabled and use the same key.
Developer Portal - Both sets of provisioning profiles (App & Extension) have been regenerated to ensure they are using the latest App Certificates with App Groups enabled and key set.
Xcode - Both App Target and WatchKit Extension Target have App Groups enabled in Capabilities and same key checked.
Xcode - Both App Target and WatchKit Extension Target have entitlements file with same key for 'com.apple.security.application-groups'.

**Comment by RomainBoulay** [comment]
"Xcode - Both App Target and WatchKit Extension Target have entitlements file with same key for 'com.apple.security.application-groups'."

That was my issue. What you describe seems to be correct, I don't see any issue here :s

**Comment by NitWitStudios** [comment]
@RomainBoulay Ugh, ok, was hoping you had something I may have missed. Yeah as far as I can tell, and reading a bunch of different walkthroughs, my App Groups are setup correctly. Then again, maybe there is some small "setting" I am missing that is causing this break.

**Comment by NitWitStudios** [comment]
Ok seems it was a bundle identifier issue.
The app, watch app and watch extension targets must all have unique bundle identifiers.

See my post here for more details: 
http://stackoverflow.com/questions/29546881/ios-watchkit-error-launching-watch-app-sperrorinvalidbundlenogizmobinarymessa
