### ISSUE TITLE
Problem In function messagePassingDirectoryPath reading Queue

### ISSUE THREAD

**Issue by neogero** [mutualmobile/MMWormhole#29]
Hi,
 I'm testing the library and I have a problem with messagePassingDirectoryPath. 
 When I generate a Message it's work correctly, but when I'm listening I have this issue: 
 
 I use listenForMessageWithIdentifier function to listen messages and when in the library flow come into  messagePassingDirectoryPath function line:

NSURL *appGroupContainer = [self.fileManager containerURLForSecurityApplicationGroupIdentifier:self.applicationGroupIdentifier]; 
always return null value

self.applicationGroupIdentifier variable have a correct value with my group.

If I override NSString *directoryPath = appGroupContainerPath; with a string with my actual path
Something like (@"/Users/gero/Library/Developer/CoreSimulator/Devices/FA4C68DD-4F63-42B3-89A5-6C611A298199/data/Containers/Shared/AppGroup/B049FE4D-EE9F-44E3-AE2A-897C05447471/wormhole/)  it's work, and I received messages correctly

Do you know if it's a issue or I need configure something?

Regards,
NeoGeRo

**Comment by HiddenJester** [comment]
That sounds like you haven't configured your app Group properly. That call you listed is a FileManager call and it will only work once you've set up the entitlement for the App Group. Look at [Apple's App Extension Programming Guide](https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW1) in the "Sharing data with Your Containing App" section. Although that section talks about User Defaults the process of configuring an App Group entitlement is the same. Once you get that working, containerURLForSecurityApplicationGroupIdentifier should start returning a valid value.
