### ISSUE TITLE
messageObject always nil

### ISSUE THREAD

**Issue by aronnelson** [mutualmobile/MMWormhole#30]
I lifted the example code and I do get notified, but the messageObject is always nil in the block handler.
In my watch kit extension, I send:
[self.wormhole passMessageObject:@{@"buttonNumber" : @(1)} identifier:@"button"];

But in my view controller, messageObject is always nil.

Any ideas? I assume it's something simple. 

[self.wormhole listenForMessageWithIdentifier:@"button" listener:^(id messageObject) {
        // The number is identified with the buttonNumber key in the message object
        NSNumber *number = [messageObject valueForKey:@"buttonNumber"];
        self.numberLabel.text = [number stringValue];
    }];

**Comment by VincentdeWit94** [comment]
Make sure you've enabled the App group in the Watch Kit Extension capabilities list. That did the trick for me.

**Comment by aronnelson** [comment]
I have enabled the app group. It's really weird and it's a problem on the app side. The extension is correctly sending the object. The problem is happening with this call: containerURLForSecurityApplicationGroupIdentifier

Now, the application does have the correct app group.

**Comment by aronnelson** [comment]
Weird. No changes, works today.
