### ISSUE TITLE
Values are not passed, if i download the file and simulate it

### ISSUE THREAD

**Issue by SanSeb** [mutualmobile/MMWormhole#35]
If i download the file and import the xcodeproject in xcode, there are no labels shown. 
It doesnt show "one" "two" "three" on the watch and not 1, 2 or 3 on the iphone. 
What's the problem here? I haven't changed any code. 
It just doesn't work like the gif shows.

Thank you

**Comment by cnstoll** [comment]
You'll need to setup the project with your own App Groups and bundle identifiers for it to work correctly. There's some instructions for how to do this on the developer portal.

https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html
