### ISSUE TITLE
listenForMessageWithIdentifier called twice

### ISSUE THREAD

**Issue by rah1991** [mutualmobile/MMWormhole#42]
Hello,
I am calling the [self.wormhole passMessageObject:@"test" identifier:@"myEvent"]; method from my apple watch. To implement the listener I am using the following code in my iOS app : -
[appDelegate.wormhole listenForMessageWithIdentifier:@"test" listener:^(id messageObject) {
       // perform action here
    }];
My issue
The "listenForMessageWithIdentifier" is called twice in my iOS app although I have called  passMessageObject from my apple watch only once. This scenario is reproduced randomly in my code. Also I have confirmed by the number of times of particular methods called by debugging watch and iOS app on the same time. 

Thanks in advance.

**Comment by cnstoll** [comment]
This could either be an issue having to do with where you setup your wormhole objects. Depending on how you initialize them in your interface controller, or how you reload interface controllers, it's possible you could have multiple wormhole instances still active, which might behave more or less like what you're seeing here. To troubleshoot that, check the addresses for the wormhole object when you hit your breakpoint.

It's more likely that this is just a manifestation of a bug with notification senders that was fixed a few days ago. Try taking the latest from master and see if that works for you. We'll be pushing that out as a new pod release for 1.2.0 sometime early next week.

Thanks,

- Conrad
