### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by halkmund** [mutualmobile/MMWormhole#43]
We encountered this issue in our WatchKit app:

ISSUE:
Calling listenForMessageWithIdentifier n times for an identifier will register n callbacks at the DarwinNotifyCenter. When passing a message, the wormhole broadcasts it n times.

SOLUTION:
A possible solution would be to change registerForNotificationsWithIdentifier by adding:

[self unregisterForNotificationsWithIdentifier:identifier];

Like this:

- (void)registerForNotificationsWithIdentifier:(NSString *)identifier {
    
    // Only registers once!!!
    [self unregisterForNotificationsWithIdentifier:identifier];
    
    CFNotificationCenterRef const center = CFNotificationCenterGetDarwinNotifyCenter();
    CFStringRef str = (__bridge CFStringRef)identifier;
    CFNotificationCenterAddObserver(center,
                                    (__bridge const void *)(self),
                                    wormholeNotificationCallback,
                                    str,
                                    NULL,
                                    CFNotificationSuspensionBehaviorDeliverImmediately);
}

**Comment by cnstoll** [comment]
Wow, you're right. Just tested it out and it got called n times. Nice catch.

Do you want to put up a PR for this? We're planning to release 1.2.0 today, and this would be a nice fix to get in for that.

I'm ok with your suggested change, and I've verified that it works. I'd love to get at least one unit test around this as well. Would you be comfortable adding that as well?

Thanks,

- Conrad

**Comment by cnstoll** [comment]
Went ahead and put up a PR for this. @halkmund what do you think? 

https://github.com/mutualmobile/MMWormhole/pull/46

**Comment by cnstoll** [comment]
Merged :)

Thanks @halkmund

**Comment by halkmund** [comment]
Hi, sorry for the late reply, but I had my email notifications tuned down for summer leave. Nice to see you got this merged!

**Comment by dhavalSA** [comment]
i have single instance of wormhole. called once in viewdidload . still sometimes listenForMessageWithIdentifier callback called multiple times . this is random behaviour . not happening all time but some time it does . i am using Version 2.0.0
