### ISSUE TITLE
Completion handler of the method listenForMessageWithIdentifier: not called

### ISSUE THREAD

**Issue by JustusvonBrandt** [mutualmobile/MMWormhole#44]
I have set up a wormhole form the main app to the Watch Kit App and the other way around. I think that I have set up the app group correctly, because Core Data sharing is working between the targets. 
After I send a message from the main app to the Watch app, the method messageWithIdentifier: finds a message, but the listener I have set up is not working. It seems to me, that the completion handler is not called, because there are no logs appearing when I try to log the messageObject.

**Comment by cnstoll** [comment]
There's a lot of debugging that might be necessary here. It's possible that the identifier you're listening for and the one you're passing a message to don't match. It's possible that your wormhole object on the watch side is getting deallocated, or that the watch app isn't active to receive the notification. It sounds like you do have app groups setup, but if you want to verify that, install the latest version of MMWormhole from master that includes some checks to verify that app groups were configured correctly.
