### ISSUE TITLE
Make listener callback more scalable

### ISSUE THREAD

**Issue by SergeyAniskin** [mutualmobile/MMWormhole#45]
Hi! At the moment lister called with only one object 'messageObject' and MMWormhole allows only one listener for identifier. To make implementation more scalable: several listeners can be registered for one identifier; one block can be used to listen for several identifiers - just add additional argument to the listener "identifier:(NSString*)identifier" this will make life mush easier and will allow to create more robust high level design implementation over MMWormhole

P.S. @cnstoll I'm using currently active MMWormhole 1.1.1

**Comment by cnstoll** [comment]
I'm having a little trouble following along here. I think you could already achieve this by having multiple wormholes, right? If you wanted one block to be called for multiple listeners, or for multiple identifiers, it seems like there are a few ways you could design your own code to make that happen. What would we do from a framework design perspective to make the library support that without making the interface more complex than it needs to be for simple use cases. It's a delicate balance to strike, and at least for now I tend to err on the simplicity side of things.

Feel free to add more detail or submit a PR that illustrates your use case.

Thanks,

- Conrad

**Comment by SergeyAniskin** [comment]
Having multiple wormholes is very expensive and error prone, especially at the moment when library have issues sending messages several times (mentioned in Issues) - so it will turn into hell of messages and broken behaviour. Adding just one additional param, that is usually a standard way of implementing callbacks, like context will give option to the user of your library to decide on his own how to use it and not to restrict. I created pull request

/Sergey

**Comment by cnstoll** [comment]
Understood. Hopefully the duplicate message issues will all be resolved in the 1.2.0 version we're about to release. I'm concerned about the perception that creating multiple wormholes is expensive. The wormhole object itself is very cheap, and having multiple wormholes for different components of a complex app should be considered a best practice from a object oriented design perspective. Hopefully the fixes for some of the messaging issues will resolve that.
