### ISSUE TITLE
Principles working

### ISSUE THREAD

**Issue by TheJson** [mutualmobile/MMWormhole#48]
Hello, I'm inexperienced at MMWormhole and I'm here to do a questions. I see that MMWormhole creates a bridge between an iOS or OS X extension so it's used to pass data or commands back and forth between the two locations.
Now I'm reading on official apple doc that there are two way to tell between the apple watch and Its Paired iPhone namely "Sharing Data with Your Containing iOS App" and "Communicating Directly with Your Containing iOS App". Now I've a doubt, what is the difference between this two methods and MMwormhole? This latter is based on one of two methods? I want to understand this library low level. Thanks

**Comment by cnstoll** [comment]
Those articles likely refer to both the App Group technology that can be used for sharing information with the containing app, and the recently added openParentApplication method that can be used to invoke a command on the containing app (parent app) even when said app is asleep in the background.

MMWormhole uses the App Group technology to share message contents between the app and the extension, and also uses a tool called Darwin Notification Center to notify either interested app or extension in changes to those message contents in real time. This is one of the documented supported ways of communicating between the app and extension. The main advantage is that this way works very well from the parent app to the extension. The openParentApplication method works very well from the watch extension to the parent app, so in the opposite direction.

Thanks,

- Conrad
