### ISSUE TITLE
Any chance to work with iOS9/watchOS 2.0?

### ISSUE THREAD

**Issue by rmvz3** [mutualmobile/MMWormhole#54]
Hi there.

My current apple watch app relies in wormhole to exchange info between the iphone and the watch. I'm updating the app to the new Swift 2 / watchOS 2 and it would be really cool if I could keep using your library because... it just works! I know Apple now says: "Watch apps that shared data with their iOS apps using a shared group container must be redesigned to handle data differently" but I wonder if this applies to a third party library like yours too. 

Thanks

**Comment by cnstoll** [comment]
Hola,

Good question. Shared group containers will not work for transferring data between your Phone app and Watch extension on watchOS 2. So yes, some changes will need to be made to your app.

The good news is we started a branch with a new subclass of MMWormhole that implements the same class interface using the new Watch Connectivity framework. So at least for some apps, you can use that branch to kick start your watchOS 2 development effort.

More info can be found here. You may want to check out the linked blog post as well.

https://github.com/mutualmobile/MMWormhole/pull/50

Thanks,

- Conrad

**Comment by rmvz3** [comment]
Oh. That’s cool. Thanks Conrad :)

-- 

Ricardo Mantero

En 6 de julio de 2015 en 0:37:27, Conrad Stoll (notifications@github.com) escrito:

Hola,

Good question. Shared group containers will not work for transferring data between your Phone app and Watch extension on watchOS 2. So yes, some changes will need to be made to your app.

The good news is we started a branch with a new subclass of MMWormhole that implements the same class interface using the new Watch Connectivity framework. So at least for some apps, you can use that branch to kick start your watchOS 2 development effort.

More info can be found here. You may want to check out the linked blog post as well.

#50

Thanks,

Conrad
