### ISSUE TITLE
Not able to pass data from an action extension

### ISSUE THREAD

**Issue by ArmandGrillet** [mutualmobile/MMWormhole#55]
Hi,

I'm trying to pass data from an action extension to its parent application through MMWormhole but it doesn't seem to work. Is it possible to use MMWormhole for this or not?

I have added in `viewDidLoad()`of my main view controller:

```swift
wormhole.listenForMessageWithIdentifier("ignore", listener: { (messageObject) -> Void in
    if let message: AnyObject = messageObject {
        print(message)
   }
})
```
But when I'm doing `wormhole.passMessageObject("yo", identifier: "ignore")`from my action request handler (used when a user touch the button linked to my app action extension) it's not printing anything. 

Passing the message object when touching a button in the application is working so I'm thinking that there is a problem due to having the application in background but I didn't find anything about this issue online.

Thank you for your work!

**Comment by neugartf** [comment]
+1
although the other way around (app -> extension)

**Comment by cnstoll** [comment]
Dang. This probably won't work if the parent app isn't running in the background already. It would work if the app is already loaded...but you don't really have a way to make sure that is the case, so if anything this would be unreliable.

One of the useful things in WatchKit is the ability for the watch to launch the parent app in the background. Unfortunately Today and Action extensions don't have the same ability :(

Sorry for the delay in responding. Thanks for filing the issue. Sorry I couldn't be of more help.
