### ISSUE TITLE
When integrating with Carthage Umbrella Header warnings are generated

### ISSUE THREAD

**Issue by mmorey** [mutualmobile/MMWormhole#56]
**Test Steps:**
1) Create a new test project in Xcode 6.4
2) Add "github "mutualmobile/MMWormhole" == 1.2.0" to `Cartfile`
3) Run `carthage update` in Terminal
4) Add the Carthage built MMWormhole iOS framework to the project following the [Carthage instructions](https://github.com/Carthage/Carthage)
5) Build
6) Xcdoe will generate the following warnings:

```
<module-includes>
<module-includes>:1:1: Umbrella header for module 'MMWormhole' does not include header 'MMWormholeCoordinatedFileTransiting.h'
<module-includes>:1:1: Umbrella header for module 'MMWormhole' does not include header 'MMWormholeFileTransiting.h'
```

**Comment by cnstoll** [comment]
Hey Matt,

Thanks for filing the issue. Sorry that I took a while responding to this. I believe I've addressed this in the new version of MMWormhole for 1.3.0 that supports watchOS. It should be merged in the next few days, but you can check out the branch referenced below if you want to see it in action. Love to hear what you think.

https://github.com/mutualmobile/MMWormhole/tree/watchOS_example_carthage

Thanks,

- Conrad
