### ISSUE TITLE
On simulator..

### ISSUE THREAD

**Issue by birnware** [mutualmobile/MMWormhole#58]
When i lock device on simulator Apple Watch extension don't work, can i use MMWormhole to send data  or to make request to iPhone when app is in background mode ?

**Comment by wizzardchao** [comment]
MMWormhole is based on Darwin Notification, which is a little different from normal notification.
From the documentation of CFNotificationCenterPostNotification:


If true, the notification is delivered to all observers immediately, even if some observers are in suspended (background) applications and they requested different suspension behavior when registering for the notification. If false, each observer’s requested suspension behavior is respected.

If center is a Darwin notification center, this value is ignored.




So the extension process and native process cannot communicate with each other when in background.
You can resort to openParentApplication:reply:, which is a single-way communication from Apple Watch to native App that can launch native App in background.

Hope this can help you.

**Comment by cnstoll** [comment]
The only thing I'd add to @wizzardchao's description is that you can be sure to construct your app such that it checks the message contents of an identifier when your app wakes back up from the background in case you missed any messages while your app was asleep :)
