### ISSUE TITLE
messageWithIdentifier not working on iOS 9 and watchOS 2 simulator

### ISSUE THREAD

**Issue by douglasd3** [mutualmobile/MMWormhole#65]
Hello, i'm struggling with a problem in my project, i cannot pass data from my iOS app to watchOS app extension, messageWithIdentifier always return nil and listenForMessageWithIdentifier is never trigged. All settings seem to be ok. App group, entitlements keys, all seems fine, i double checked every setting in all targets.

Anyone have any idea of what could be causing the problem? Simulator issues maybe?

**Comment by cnstoll** [comment]
Hi Doug,

Are you building a watchOS 2 app? If so, are you using the new MMWormholeSession and MMWormholeSessionTransiting types in MMWormhole v2.0? There is a brief description of how to use that here: https://github.com/mutualmobile/MMWormhole#communication-with-watchconnectivity

The main reason I ask this is that App Groups aren't really involved in watch <-> phone communication in watchOS 2, so if you're still relying on those for inter device communication you'll run into some issues. They can still be relevant for storing data locally on device though, but it doesn't seem from the issue description that is what you're having trouble with.

Finally, one thing I've noticed frequently with watchOS 2 development is that WatchConnectivity will sometimes fail if the Watch app isn't correctly registered as "installed" with the OS. This happens pretty frequently when using Build & Run from Xcode. The best workaround is to go to the "Apple Watch" app from Apple on the iPhone (or iOS Simulator) and find your app and toggle it's installed toggle on and off to re-install the watch app.

Thanks,

- Conrad

**Comment by cnstoll** [comment]
Closing for now. Feel free to re-open if that doesn't address the issue.
