### ISSUE TITLE
installation with CocoaPods and use_frameworks! not working in WatchKit extension

### ISSUE THREAD

**Issue by haemi** [mutualmobile/MMWormhole#67]
I try to install MMWormhole with cocoapods in my project (mixed Objective-C / Swift)

```
platform :ios, '8.0'

inhibit_all_warnings!

use_frameworks!

target 'MyApp' do
    pod 'MMWormhole', '2.0.0'
end

target 'kontoalarm WatchKit Extension' do
    pod 'MMWormhole', '2.0.0'
end
```

In the bridging header I include MMWormhole as well:

```
#import <MMWormhole/MMWormhole.h>
```

But when using it in swift-files of my WatchKit-extension I get

```
Use of unresolved identifier 'MMWormhole'
```

Am I missing something?

**Comment by madspacer** [comment]
What's the error you've encountered?

**Comment by cnstoll** [comment]
There's a useful response here about installing with CocoaPods, but I believe this has been resolved at this point. Apologies for the delayed response.
