### ISSUE TITLE
Not getting message in Swift

### ISSUE THREAD

**Issue by TaimoorAli-Sematree** [mutualmobile/MMWormhole#70]
I'm facing some issues. Kindly answer me to fix the issue. On iPhone app side I'm using this

let wormhole : MMWormhole = MMWormhole(applicationGroupIdentifier: "group.com.xyz", optionalDirectory: "ProjectDataDict")
wormhole.passMessageObject("message recieved or not?", identifier: "ProjectData")

Just this code on iPhone side no. And on swift side I am doing this

wormhole = MMWormhole(applicationGroupIdentifier: "group.com.xyz", optionalDirectory: "ProjectDataDict")
let messageObj = wormhole.messageWithIdentifier("ProjectData")

But it is not giving me any message. Kindly tell me the issue. . .

**Comment by unigamestudio** [comment]
i have the same problem

**Comment by roeemins** [comment]
and so do I

**Comment by crinos9** [comment]
i have same problem same problem with obtaining msgs. 

On iphone side i pass object by calling wormhole.passMessageObject.
On watch side im trying to obtain the msg by calling wormhole.messageWithIdentifier, but it returns nil. I also tried to us wormhole.listenForMessageWithIdentifier but block is not called.

**Comment by cashish** [comment]
i too  tried to using  wormhole.listenForMessageWithIdentifier but listener block is not called.
any work around or fix?

**Comment by cnstoll** [comment]
Can you tell me more about your project configuration? Are you on watchOS 2 or 3? Are your app groups setup correctly? Does messageWithIdentifier work even when listenForMessageWithIdentifier fails?

Need a little more information to help debug, but this sounds like a configuration issue to me.
