### ISSUE TITLE
iPhone 4S Crash

### ISSUE THREAD

**Issue by chrisdhaan** [mutualmobile/MMWormhole#71]
Currently if you use MMWormHole watchOS 2 functionality on the iPhone 4S the following crash will occur:

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WCSession updateApplicationContext:error:]: applicationContext cannot be nil.'

Right now I have a work around that checks to make sure the device type is greater than 4S but this might be something you want to check in MMWormHole.

**Comment by chrisdhaan** [comment]
This is the code I added before all MMWormHole calls in my project to stop the crash:

if ([WCSession isSupported]) { 
     // project code
}

**Comment by cnstoll** [comment]
I'm adding a fix for this! Adding the isSupported check to the application context and file transfer methods. It's already accounted for in the sendMessage type.

**Comment by cnstoll** [comment]
https://github.com/mutualmobile/MMWormhole/pull/79
