### ISSUE TITLE
library not found for -lMMWormhole

### ISSUE THREAD

**Issue by vagishmm** [mutualmobile/MMWormhole#76]
ld: warning: directory not found for option '-L/Users/Desktop/testbridge/platforms/ios/build/Debug-iphoneos' ld: library not found for -lMMWormhole clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by steve228uk** [comment]
@vagishmm I had this error when installing via CocoaPods. Check that `$(inherited)` is in your project's search paths.
