### ISSUE TITLE
cordova-plugin-watch based on MMWormhole

### ISSUE THREAD

**Issue by helmuthva** [mutualmobile/MMWormhole#8]
Dear Mutualmobile team,

we just open sourced an Apache Cordova plugin based on your MMWormhole:

https://github.com/20steps/cordova-plugin-watch

Please have a look and tell us if you need additional mentioning/backlinks from 20steps/cordova-plugin-watch back to you.

Yours, 20steps.

**Comment by cnstoll** [comment]
Hey Guys,

Looks great! Thanks for doing that and for letting me know :)

Cheers,

- Conrad
