### ISSUE TITLE
how can i use for passing value each other？

### ISSUE THREAD

**Issue by Fengur** [mutualmobile/MMWormhole#81]
A to  B, then B to A .
I make a new warmhole,but it seems not work, should i change group id when i user 'B to A' ?

**Comment by cnstoll** [comment]
Hi,

I think we'd need more information to understand your use case, but in general, the same group identifier should be fine in both directions.

Thanks,

- Conrad

**Comment by Fengur** [comment]
thamk you ,my problem had been solved,sorry to bother you
