### ISSUE TITLE
Can I get the size of data stored with MMWormhole?

### ISSUE THREAD

**Issue by pgbo** [mutualmobile/MMWormhole#83]
I can't find any methods to get the size of data stored with MMWormhole. It'll be more wonderful if you make a method to calculate the size of stored data! 😊

**Comment by cnstoll** [comment]
That's a neat request. If it's just the data stored in the shared app group container, and you specified a sub-directory, then I think you can just use NSFileManager to get that. But I can keep that around as a feature request too.

**Comment by pgbo** [comment]
That's great! 👍
